check_config:
  description: Check the Open Power Power configuration files for errors. Errors will be displayed in the Open Power Power log.

reload_core_config:
  description: Reload the core configuration.

restart:
  description: Restart the Open Power Power service.

stop:
  description: Stop the Open Power Power service.

toggle:
  description: Generic service to toggle devices on/off under any domain. Same usage as the light.turn_on, switch.turn_on, etc. services.
  fields:
    entity_id:
      description: The entity_id of the device to toggle on/off.
      example: light.living_room

turn_on:
  description: Generic service to turn devices on under any domain. Same usage as the light.turn_on, switch.turn_on, etc. services.
  fields:
    entity_id:
      description: The entity_id of the device to turn on.
      example: light.living_room

turn_off:
  description: Generic service to turn devices off under any domain. Same usage as the light.turn_on, switch.turn_on, etc. services.
  fields:
    entity_id:
      description: The entity_id of the device to turn off.
      example: light.living_room

update_entity:
  description: Force one or more entities to update its data
  fields:
    entity_id:
      description: One or multiple entity_ids to update. Can be a list.
      example: light.living_room
